apiVersion: v1
kind: PersistentVolume
metadata:
  name: mpi-test-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/lyx0309/mpi-test/code_input"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mpi-test-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
